<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1670481809555' stop='1670482263752'>
    <name>TC 2 : Login User</name>
    <title>TC 2 : Login User</title>
    <test-cases>
        <test-case start='1670481809557' status='failed' stop='1670482109566'>
            <name>1 Login with correct credentials</name>
            <title>1 Login with correct credentials</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-108.0.5359.73'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async function did not complete within 300000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)</message>
                <stack-trace>    at &lt;Jasmine>
                    at listOnTimeout (node:internal/timers:564:17)
                    at processTimers (node:internal/timers:507:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1670482109567' status='failed' stop='1670482263746'>
            <name>2 Delete Account</name>
            <title>2 Delete Account</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-108.0.5359.73'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>CompoundError: One or more errors occurred. ---
                
                    error properties: Object({ input: undefined, code: 'ECONNRESET', timings: Object({ start: 1670482169626, socket: 1670482169627, lookup: 1670482169628, connect: 1670482169628, secureConnect: undefined, upload: 1670482169629, response: undefined, end: undefined, error: 1670482263720, abort: undefined, phases: Object({ wait: 1, dns: 1, tcp: 0, tls: undefined, request: 1, firstByte: undefined, download: undefined, total: 94094 }) }), options: Options({ _unixOptions: undefined, _internals: Object({ request: undefined, agent: Object({ http: Agent({ _events: null({ free: Function, newListener: Function }), _eventsCount: 2, _maxListeners: undefined, defaultPort: 80, protocol: 'http:', options: null({ keepAlive: true, noDelay: true, path: null }), requests: null({  }), sockets: null({ localhost:9515:: [ Socket({ connecting: false, _hadError: true, _parent: null, _host: 'localhost', _closeAfterHandlingError: false, _readableState: ReadableState, _events: null, _eventsCount: 7, _maxListeners: undefined, _writa ...
                        at Object.onceWrapper (node:events:628:26)
                        at ClientRequest.emit (node:events:525:35)
                        at ClientRequest.emit (node:domain:489:12)
                        at Socket.socketErrorListener (node:_http_client:488:9)
                        at Socket.emit (node:events:513:28)
                        at Socket.emit (node:domain:489:12)
                        at emitErrorNT (node:internal/streams/destroy:151:8)
                        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                        at processTicksAndRejections (node:internal/process/task_queues:82:21)
                        at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
                --- End of stack trace ---
                
                        at processTicksAndRejections (node:internal/process/task_queues:95:5)
                        at UserContext.&lt;anonymous> (D:\MY\TestFile\test\specs\/2loginUser.test.js:18:9)
                --- End of stack trace ---
                </message>
                <stack-trace>Error: CompoundError: One or more errors occurred. ---
                
                    error properties: Object({ input: undefined, code: 'ECONNRESET', timings: Object({ start: 1670482169626, socket: 1670482169627, lookup: 1670482169628, connect: 1670482169628, secureConnect: undefined, upload: 1670482169629, response: undefined, end: undefined, error: 1670482263720, abort: undefined, phases: Object({ wait: 1, dns: 1, tcp: 0, tls: undefined, request: 1, firstByte: undefined, download: undefined, total: 94094 }) }), options: Options({ _unixOptions: undefined, _internals: Object({ request: undefined, agent: Object({ http: Agent({ _events: null({ free: Function, newListener: Function }), _eventsCount: 2, _maxListeners: undefined, defaultPort: 80, protocol: 'http:', options: null({ keepAlive: true, noDelay: true, path: null }), requests: null({  }), sockets: null({ localhost:9515:: [ Socket({ connecting: false, _hadError: true, _parent: null, _host: 'localhost', _closeAfterHandlingError: false, _readableState: ReadableState, _events: null, _eventsCount: 7, _maxListeners: undefined, _writa ...
                        at Object.onceWrapper (node:events:628:26)
                        at ClientRequest.emit (node:events:525:35)
                        at ClientRequest.emit (node:domain:489:12)
                        at Socket.socketErrorListener (node:_http_client:488:9)
                        at Socket.emit (node:events:513:28)
                        at Socket.emit (node:domain:489:12)
                        at emitErrorNT (node:internal/streams/destroy:151:8)
                        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                        at processTicksAndRejections (node:internal/process/task_queues:82:21)
                        at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
                --- End of stack trace ---
                
                        at processTicksAndRejections (node:internal/process/task_queues:95:5)
                        at UserContext.&lt;anonymous> (D:\MY\TestFile\test\specs\/2loginUser.test.js:18:9)
                --- End of stack trace ---
                
                    at getErrorFromFailedTest (file:///D:/MY/TestFile/node_modules/@wdio/allure-reporter/build/utils.js:71:60)
                    at AllureReporter.onTestFail (file:///D:/MY/TestFile/node_modules/@wdio/allure-reporter/build/index.js:228:38)
                    at AllureReporter.&lt;anonymous> (file:///D:/MY/TestFile/node_modules/@wdio/reporter/build/index.js:118:18)
                    at AllureReporter.emit (node:events:513:28)
                    at AllureReporter.emit (node:domain:489:12)
                    at file:///D:/MY/TestFile/node_modules/@wdio/runner/build/reporter.js:47:56
                    at Array.forEach (&lt;anonymous>)
                    at BaseReporter.emit (file:///D:/MY/TestFile/node_modules/@wdio/runner/build/reporter.js:47:25)
                    at JasmineReporter.emit (file:///D:/MY/TestFile/node_modules/@wdio/jasmine-framework/build/reporter.js:154:24)
                    at JasmineReporter.specDone (file:///D:/MY/TestFile/node_modules/@wdio/jasmine-framework/build/reporter.js:85:14)
                    at UserContext.fn (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7801:23)
                    at QueueRunner.attempt (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7629:40)
                    at QueueRunner.run (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7667:27)
                    at QueueRunner.execute (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7521:10)
                    at queueRunnerFactory (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1527:35)
                    at D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1628:16
                    at D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7775:9
                    at new Promise (&lt;anonymous>)
                    at dispatch (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7774:14)
                    at ReportDispatcher.specDone (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7743:18)
                    at reportSpecDone (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1851:16)
                    at SuiteBuilder.specResultCallback [as specResultCallback_] (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1840:7)
                    at Spec.resultCallback (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:10061:16)
                    at UserContext.fn (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:869:14)
                    at QueueRunner.attempt (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7640:40)
                    at QueueRunner.run (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7667:27)
                    at runNext (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7571:16)
                    at D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7577:11
                    at D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7463:9
                    at onPromiseRejection (D:\MY\TestFile\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:7655:7)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>